import = ["/home/capgodc/.config/alacritty/cyberdream.toml"]

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"

[window]
decorations = "full"
opacity = 0.90

[window.dimensions]
columns = 140
lines = 40

[window.padding]
x = 5
y = 5
